profile:
  name: "Production Day"
  mode: simulation
  description: "Typical office workload 9-18, minimal overnight"

load_pattern:
  type: hourly
  baseline_qps: 100
  min_multiplier: 0.1
  max_multiplier: 10.0
  hourly_multipliers:
    0: 0.15    # night - very low
    1: 0.10    # night - minimum
    2: 0.10
    3: 0.10
    4: 0.15    # early morning
    5: 0.20
    6: 0.40    # early birds arriving
    7: 0.70    # morning commute
    8: 1.20    # offices opening
    9: 1.50    # morning peak
    10: 1.40
    11: 1.30
    12: 0.90   # lunch break
    13: 1.10   # post-lunch
    14: 1.40   # afternoon peak
    15: 1.35
    16: 1.20
    17: 0.90   # end of day
    18: 0.50   # offices closing
    19: 0.30
    20: 0.25
    21: 0.20
    22: 0.18
    23: 0.15

workload_distribution:
  read: 75
  write: 25

connection_pattern:
  min_connections: 5
  max_connections: 50
  scale_with_load: true
